import jsPDF from 'jspdf';
import type { AIItinerary } from '@/contexts/TripContext';

export const generateItineraryPDF = async (itinerary: AIItinerary, tripTitle: string) => {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 15;
  let yPosition = margin;

  // Helper function to check if we need a new page
  const checkPageBreak = (requiredSpace: number) => {
    if (yPosition + requiredSpace > pageHeight - margin) {
      pdf.addPage();
      yPosition = margin;
      return true;
    }
    return false;
  };

  // Title
  pdf.setFontSize(24);
  pdf.setTextColor(138, 120, 184); // Looper lavender color
  pdf.text(tripTitle || 'Your Trip Itinerary', pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 15;

  // Date
  pdf.setFontSize(10);
  pdf.setTextColor(100, 100, 100);
  pdf.text(`Generated on ${new Date().toLocaleDateString()}`, pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 15;

  // Loop through each day
  for (let dayIndex = 0; dayIndex < itinerary.days.length; dayIndex++) {
    const day = itinerary.days[dayIndex];
    
    checkPageBreak(20);

    // Day header
    pdf.setFillColor(203, 216, 59); // Pear color
    pdf.rect(margin, yPosition, pageWidth - 2 * margin, 10, 'F');
    pdf.setFontSize(16);
    pdf.setTextColor(0, 0, 0);
    pdf.text(`Day ${day.dayNumber}`, margin + 5, yPosition + 7);
    yPosition += 15;

    // Loop through time slots (morning, afternoon, evening)
    const timeSlots = [
      { period: 'Morning', slot: day.timeSlots.morning },
      { period: 'Afternoon', slot: day.timeSlots.afternoon },
      { period: 'Evening', slot: day.timeSlots.evening }
    ];

    for (const { period, slot } of timeSlots) {
      if (!slot || !slot.location) continue;

      checkPageBreak(40);

      // Period and time
      pdf.setFontSize(11);
      pdf.setTextColor(138, 120, 184);
      pdf.text(`${period} - ${slot.time || 'N/A'} - ${slot.transportMode || 'Walk'}`, margin, yPosition);
      yPosition += 7;

      // Location name
      pdf.setFontSize(14);
      pdf.setTextColor(0, 0, 0);
      const locationName = slot.location.name || 'Unknown Location';
      pdf.text(locationName, margin, yPosition);
      yPosition += 7;

      // Activities
      if (slot.activities && slot.activities.length > 0) {
        pdf.setFontSize(10);
        pdf.setTextColor(80, 80, 80);
        
        slot.activities.forEach(activity => {
          checkPageBreak(5);
          pdf.text(`• ${activity}`, margin + 5, yPosition);
          yPosition += 5;
        });
      }

      // Travel details
      if (slot.travelTime || slot.duration) {
        checkPageBreak(5);
        pdf.setFontSize(9);
        pdf.setTextColor(120, 120, 120);
        const travelInfo = [
          slot.duration ? `Duration: ${slot.duration}` : null,
          slot.travelTime ? `Travel time: ${slot.travelTime}` : null
        ].filter(Boolean).join(' | ');
        pdf.text(travelInfo, margin + 5, yPosition);
        yPosition += 5;
      }

      // Notes
      if (slot.notes) {
        checkPageBreak(5);
        pdf.setFontSize(9);
        pdf.setTextColor(100, 100, 100);
        pdf.text(`📝 ${slot.notes}`, margin + 5, yPosition);
        yPosition += 5;
      }

      // Add spacing between locations
      yPosition += 5;

      // Add a separator line
      pdf.setDrawColor(200, 200, 200);
      pdf.line(margin, yPosition, pageWidth - margin, yPosition);
      yPosition += 7;
    }

    // Add extra space between days
    yPosition += 5;
  }

  // Footer on last page
  const totalPages = pdf.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text(
      `Page ${i} of ${totalPages} | Generated by Looper`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
  }

  // Save the PDF
  const fileName = `${tripTitle.replace(/[^a-z0-9]/gi, '_')}_itinerary.pdf`;
  pdf.save(fileName);
};
